// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC9--AxwU1pA04ffgGdl55U5fF8-goJKw',
    appId: '1:408497106915:web:8ae45454a7d101d43a7ad6',
    messagingSenderId: '408497106915',
    projectId: 'chat-app-81750',
    authDomain: 'chat-app-81750.firebaseapp.com',
    storageBucket: 'chat-app-81750.appspot.com',
    measurementId: 'G-19R5EJXMBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKhV0T_jR5mQ60hgXIrwlXYJ4XiUP0rGc',
    appId: '1:408497106915:android:eeb496c0e9e0486a3a7ad6',
    messagingSenderId: '408497106915',
    projectId: 'chat-app-81750',
    storageBucket: 'chat-app-81750.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2AxlefR8dcI7UBO513lG8yCBPX4GYfro',
    appId: '1:408497106915:ios:95d68679ab6bc7663a7ad6',
    messagingSenderId: '408497106915',
    projectId: 'chat-app-81750',
    storageBucket: 'chat-app-81750.appspot.com',
    iosBundleId: 'com.example.chatappproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2AxlefR8dcI7UBO513lG8yCBPX4GYfro',
    appId: '1:408497106915:ios:95d68679ab6bc7663a7ad6',
    messagingSenderId: '408497106915',
    projectId: 'chat-app-81750',
    storageBucket: 'chat-app-81750.appspot.com',
    iosBundleId: 'com.example.chatappproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDC9--AxwU1pA04ffgGdl55U5fF8-goJKw',
    appId: '1:408497106915:web:99d4f208e677af8b3a7ad6',
    messagingSenderId: '408497106915',
    projectId: 'chat-app-81750',
    authDomain: 'chat-app-81750.firebaseapp.com',
    storageBucket: 'chat-app-81750.appspot.com',
    measurementId: 'G-7P6Z8YXVQD',
  );

}